defaultContentLanguage: zh-Hans
baseURL: "https://shaneyao.com"
params:
  displayFullLangName: true

theme: 
 - PaperMod

module:
  mounts:
  - source: shane_pkm/Publish/Posts
    target: content/posts
  - source: shane_pkm/Publish/GameDev
    target: content/gamedev
  - source: shane_pkm/Publish/Enthusiasm
    target: content/enthusiasm
markup:
  goldmark:
    renderer:
      unsafe: true

services:
  googleAnalytics:
    id: 'G-9BYF76TH10'