defaultContentLanguage: zh-Hans
baseURL: "https://shaneyao.com"
params:
  displayFullLangName: true

theme: 
 - paperMod

module:
  mounts:
  - source: shane_pkm/Publish/Posts
    target: content/posts
  - source: shane_pkm/Publish/GameDev
    target: content/gamedev
markup:
  goldmark:
    renderer:
      unsafe: true

services:
  googleAnalytics:
    id: 'G-9BYF76TH10'