main:
- name: "Home"
  pageRef: /
  weight: 1
- name: "Posts"
  pageRef: /posts
  weight: 5
- name: "GameDev"
  pageRef: /gamedev
  weight: 20
- name: "Enthusiasm"
  pageRef: /enthusiasm
  weight: 20
- name: "Issues"
  pageRef: /issues
  weight: 30