colorScheme: congo
defaultAppearance: light
autoSwitchAppearance: true
defaultThemeColor: "#FFFFFF"
enableSearch: false
enableCodeCopy: false
enableImageLazyLoading: true
enableImageWebp: true
fingerprintAlgorithm: sha256
header:
  layout: basic
  showTitle: true
footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: false
  showScrollToTop: true
homepage:
  layout: profile
  showRecent: false
  recentLimit: 5
article:
  showTaxonomies: true
  showDate: true
  showDateUpdated: true
  showAuthor: true
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: false
  showTableOfContents: true
  showWordCount: false
  showComments: false
list:
  showTaxonomies: true
  showBreadcrumbs: false
  showSummary: false
  showTableOfContents: false
  groupByYear: true
  paginationWidth: 1
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
fathomAnalytics: {}
plausibleAnalytics: {}
verification: {}
mainSections : 
 - "posts"
 - "gamedev"