colorScheme: congo
defaultAppearance: light
autoSwitchAppearance: true
defaultThemeColor: "#FFFFFF"
enableSearch: false
enableCodeCopy: false
enableImageLazyLoading: true
enableImageWebp: true
fingerprintAlgorithm: sha256
header:
  layout: basic
  showTitle: true
footer:
  showCopyright: true
  showThemeAttribution: true
  showAppearanceSwitcher: false
  showScrollToTop: true
homepage:
  layout: profile
  showRecent: false
  recentLimit: 5
article:
  showTaxonomies: true
  showDate: true
  showDateUpdated: true
  showAuthor: true
  showBreadcrumbs: false
  showDraftLabel: true
  showEdit: false
  editAppendPath: true
  showHeadingAnchors: true
  showPagination: true
  invertPagination: false
  showReadingTime: false
  showTableOfContents: true
  showWordCount: false
  showComments: true
list:
  showTaxonomies: true
  showBreadcrumbs: false
  showSummary: false
  showTableOfContents: false
  groupByYear: true
  paginationWidth: 1
sitemap:
  excludedKinds:
    - taxonomy
    - term
taxonomy:
  showTermCount: true
fathomAnalytics: {}
plausibleAnalytics: {}
verification: {}
mainSections : 
 - "posts"
 - "gamedev"
 


giscus:
  repo: "shane-yao/shaneyao"
  repoId: "MDEwOlJlcG9zaXRvcnkyODkwNTg0NzI"
  category: "Announcements"
  categoryId: "DIC_kwDOETquqM4CzfkJ"
  mapping: "pathname"
  strict: "0"
  reactionsEnabled: "1"
  emitMetadata: "0"
  inputPosition: "bottom"
  lightTheme: "light"
  darkTheme: "dark"
  lang: "zh-CN"
  discussionTitle: 欢迎来到评论区
  discussionSubtitle: 感谢您的耐心阅读！如需交流，请留个评论吧！